servers:
  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5 # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling: # 长轮询拓展
        enabled: false # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      # middlewares:
      #   <<: *default # 引用默认中间件
      post: # 反向HTTP POST地址列表
        - url: "http://127.0.0.1:8000"
          secret: ""
